[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/simple-mcp"
  status = 200
  force = true

[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/simple-mcp"
  status = 200
  force = true